### ISSUE TITLE
fix README

### ISSUE THREAD

**Issue by UbeCc** [mattbishop/fastify-https-always#1]
```
fastify.register(httpsAlwaysPlugin, httpsAlwaysOpts);
```
for typescript instruction.

Thanks for your plugin!

**Comment by mattbishop** [comment]
Thanks for your report. What is your question though? The instructions are correct. Are you seeing an error? Please add to this report if so.

**Comment by UbeCc** [comment]
Sorry, I didn't describe clearly. It's a minor typo, I thought. 
In README.md, you provide instruction for `typescript`
```
import Fastify from "fastify"
import httpsAlwaysPlugin, {HttpsAlwaysOptions} from "fastify-https-always"

const fastify = Fastify({
    trustProxy: true
})

// leave out options whose default is suitable
const httpsAlwaysOpts: HttpsAlwaysOptions = { 
  productionOnly: false, 
  redirect: false,
  httpsPort: 8443
}

fastify.register(allowPlugin, httpsAlwaysOpts)
```

We see the last line: 
`fastify.register(allowPlugin, httpsAlwaysOpts)`
There is no `allowPlugin`, but `httpsAlwaysPlugin`, so I change it to `fastify.register(httpsAlwaysPlugin, httpsAlwaysOpts);` and it works.

I'm not sure if it is fastify-version dependent though. Thanks!

**Comment by mattbishop** [comment]
Oooh, right. Thanks for clarifying! I cloned another fastify plugin I wrote called [fastify-allow](https://github.com/mattbishop/fastify-allow) but didn't update the references completely.
